development:
  adapter: postgresql
  database: newstore
  pool: 5
  username: ethan
  password: desmadre09,
  timeout: 5000

test:
  adapter: postgresql
  database: newstore_test
  pool: 5
  username: ethan
  password: desmadre09,
  timeout: 5000
